name: aradeepopsis-shiny-v1.3
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-shiny=1.5.0
  - conda-forge::r-shinythemes=1.1.2
  - conda-forge::r-shinycssloaders=1.0.0
  - conda-forge::r-slickr=0.5.0
  - conda-forge::r-corrplot=0.84
  - conda-forge::r-jpeg=0.1_8.1
  - r::r-radarchart=0.3.1
