name: aradeepopsis-dpp-v1.3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - conda-forge::scipy=1.5.0
  - conda-forge::opt-einsum=3.0.0
  - conda-forge::tqdm=4.47.0
  - conda-forge::pillow=7.1.2
  - pip:
    - tensorflow==1.15
    - opencv-python==4.2.0.34
    - https://github.com/p2irc/deepplantphenomics/archive/2.1.0.tar.gz
